### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by tmarble** [bhauman/flappy-bird-demo#5]
This repo does not have a LICENSE file nor does it have a license declaration in `project.clj` nor in the (non-existant) `README.md`.

FWIW I'm working on a PR to close #3, update dependencies, add a minimal `README.md` file and I would be happy to add a LICENSE -- if I only knew [which one you want](http://choosealicense.com/)!

**Comment by bhauman** [comment]
Feel free to add the eclipse license like figwheel.  Thank you!
